add deduplication of keys in secretsProvided

diff --git a/.test/azure/single-aks-acr/Taskfile.yaml b/.test/azure/single-aks-acr/Taskfile.yaml
--- a/.test/azure/single-aks-acr/Taskfile.yaml
+++ b/.test/azure/single-aks-acr/Taskfile.yaml
@@ -33,13 +33,12 @@ tasks:
         branch_name=$(git rev-parse --abbrev-ref HEAD)
         codebundle=$(basename "$(dirname "$PWD")")
 
-
         # Generate workspaceInfo.yaml with fetched cluster details
         cat <<EOF > workspaceInfo.yaml
         workspaceName: "$RW_WORKSPACE"
         workspaceOwnerEmail: authors@runwhen.com
-        defaultLocation: location-01
-        defaultLOD: detailed
+        defaultLocation: bd97d852-7cfe-4f24-8697-af70a1d8244a
+        defaultLOD: basic
         cloudConfig:
           azure:
             subscriptionId: "$ARM_SUBSCRIPTION_ID"
@@ -49,15 +48,18 @@ tasks:
             aksClusters: 
               clusters: 
                 - name: cluster1
-                  server: https://cluster1-bmzw343t.hcp.eastus.azmk8s.io:443
+                  server: https://cluster1-z3hr4n51.hcp.eastus.azmk8s.io:443
                   resource_group: workspace-utils_azure-rw-acr-helm-update
-                  subscriptionId: 2a0cf760-baef-4446-b75c-75c4f8a6267f
+                  subscriptionId: $ARM_SUBSCRIPTION_ID
             resourceGroupLevelOfDetails:
               workspace-utils_azure-rw-acr-helm-update: detailed
         codeCollections:
         - repoURL: "https://github.com/stewartshea/rw-workspace-utils"
           branch: "rw-acr-helm"
           codeBundles: ["azure-rw-acr-helm-update"]
+        - repoURL: "https://github.com/runwhen-contrib/rw-cli-codecollection"
+          branch: "main"
+          codebundles: ["k8s-namespace-healthcheck"]
         custom: 
           kubernetes_distribution_binary: kubectl
           private_registry: azure_acr
@@ -70,7 +72,7 @@ tasks:
     desc: "Run RunWhen Local Discovery on test infrastructure"
     cmds:
       - |
-        BUILD_DIR=/home/runwhen/runwhen-local/src
+        BUILD_DIR=../../../src
         CONTAINER_NAME="RunWhenLocal"
         if docker ps -q --filter "name=$CONTAINER_NAME" | grep -q .; then
           echo "Stopping and removing existing container $CONTAINER_NAME..."
@@ -145,4 +147,83 @@ tasks:
       - |
         rm -rf output
         rm workspaceInfo.yaml
+    silent: true
+
+  upload-slxs:
+    desc: "Upload SLX files to the appropriate URL"
+    env:
+      RW_WORKSPACE: "{{.RW_WORKSPACE}}"
+      RW_API_URL: "{{.RW_API}}"
+      RW_PAT: "{{.RW_PAT}}"
+    cmds:
+      - |
+        BASE_DIR="output/workspaces/${RW_WORKSPACE}/slxs"
+        if [ ! -d "$BASE_DIR" ]; then
+          echo "Directory $BASE_DIR does not exist. Upload aborted."
+          exit 1
+        fi
+
+        for dir in "$BASE_DIR"/*; do
+          if [ -d "$dir" ]; then
+            SLX_NAME=$(basename "$dir")
+            PAYLOAD=$(jq -n --arg commitMsg "Creating new SLX $SLX_NAME" '{ commitMsg: $commitMsg, files: {} }')
+            for file in slx.yaml runbook.yaml sli.yaml; do
+              if [ -f "$dir/$file" ]; then
+                CONTENT=$(cat "$dir/$file")
+                PAYLOAD=$(echo "$PAYLOAD" | jq --arg fileContent "$CONTENT" --arg fileName "$file" '.files[$fileName] = $fileContent')
+              fi
+            done
+
+            URL="https://${RW_API_URL}/api/v3/workspaces/${RW_WORKSPACE}/branches/main/slxs/${SLX_NAME}"
+            echo "Uploading SLX: $SLX_NAME to $URL"
+            response_code=$(curl -X POST "$URL" \
+              -H "Authorization: Bearer $RW_PAT" \
+              -H "Content-Type: application/json" \
+              -d "$PAYLOAD" \
+              -w "%{http_code}" -o /dev/null -s)
+            
+            if [[ "$response_code" == "200" || "$response_code" == "201" ]]; then
+              echo "Successfully uploaded SLX: $SLX_NAME to $URL"
+            elif [[ "$response_code" == "405" ]]; then
+              echo "Failed to upload SLX: $SLX_NAME to $URL. Method not allowed (405)."
+            else
+              echo "Failed to upload SLX: $SLX_NAME to $URL. Unexpected response code: $response_code"
+            fi
+          fi
+        done
+    silent: true
+  delete-slxs:
+    desc: "Delete SLX objects from the appropriate URL"
+    env:
+      RW_WORKSPACE: '{{.RW_WORKSPACE | default "my-workspace"}}'
+      RW_API_URL: "{{.RW_API}}"
+      RW_PAT: "{{.RW_PAT}}"
+    cmds:
+      - task: check-rwp-config
+      - |
+        BASE_DIR="output/workspaces/${RW_WORKSPACE}/slxs"
+        if [ ! -d "$BASE_DIR" ]; then
+          echo "Directory $BASE_DIR does not exist. Deletion aborted."
+          exit 1
+        fi
+
+        for dir in "$BASE_DIR"/*; do
+          if [ -d "$dir" ]; then
+            SLX_NAME=$(basename "$dir")
+            URL="https://${RW_API_URL}/api/v3/workspaces/${RW_WORKSPACE}/branches/main/slxs/${SLX_NAME}"
+            echo "Deleting SLX: $SLX_NAME from $URL"
+            response_code=$(curl -X DELETE "$URL" \
+              -H "Authorization: Bearer $RW_PAT" \
+              -H "Content-Type: application/json" \
+              -w "%{http_code}" -o /dev/null -s)
+            
+            if [[ "$response_code" == "200" || "$response_code" == "204" ]]; then
+              echo "Successfully deleted SLX: $SLX_NAME from $URL"
+            elif [[ "$response_code" == "405" ]]; then
+              echo "Failed to delete SLX: $SLX_NAME from $URL. Method not allowed (405)."
+            else
+              echo "Failed to delete SLX: $SLX_NAME from $URL. Unexpected response code: $response_code"
+            fi
+          fi
+        done
     silent: true
