Support for location id/name labels and generated-by annotation (#675)
* Support for location id/name labels and generated-by annotation

- the location labels were added to assist in troubleshooting
- these are added to all generated SLX/workflow resources, at least
  assuming they are following the convention to include the common
  labels and annotation templates in their gen rules templates
- the location values typically come from the uploadInfo.yaml file and
  are set by PAPI when that file is downloaded to RWL
- although note that as of now the PAPI endpoint to generate the
  upload info file hasn't been updated to include the location name yet,
  so if you want to test that you need to hand tweak the upload info file.
  The name of the setting in there is "defaultLocationName".
- the generated-by annotation will be used in the new PAPI reconciliation
  logic to be able to distinguish between resources that come from
  different locations
- The value of the generated-by annotation is:
  workspace-builder:<location-name>. If no location name is specified
  in the upload info file, then it used the location id value.
- there's also some code in this commit that reverts back to passing the
  kubeconfig contents in the request to the workspace builder service
  rather than reading it from the container file system. This is to go
  back to the original service design that didn't assume/require that
  the workspace builder service share a file system with the caller, which
  was undesirable from a service design standpoint. This change also
  facilitated local development/debugging of the workspace builder service
  where it was undesirable to have to have the kubeconfig at a hard-coded
  location in the file system and in a root-level workspace-builder
  directory.
- removed support for top-level settings for the legacy top-level
  Kubernetes indexing settings for things like the kubeconfig file and the
  namespace LOD settings. These must now be specified with the new config
  structure where they are in the cloudConfig/kubernetes block (which I
  think hopefully everyone has already switched over to anyway).

* fix azure config generation
fix taskfile

* remove print statement. add/update test infra

* test infra for helm install with PR based image

* test updates

* fix managed identity test code. version bump.

* update readmes

---------

Co-authored-by: Rob Vaterlaus <rob.vaterlaus@runwhen.com>
Co-authored-by: Shea Stewart <shea.stewart@runwhen.com>

diff --git a/.test/azure/aks-helm-installed-sp/Taskfile.yaml b/.test/azure/aks-helm-installed-sp/Taskfile.yaml
--- a/.test/azure/aks-helm-installed-sp/Taskfile.yaml
+++ b/.test/azure/aks-helm-installed-sp/Taskfile.yaml
@@ -22,7 +22,7 @@ tasks:
   generate-rwl-config:
     desc: "Generate RunWhen Local configuration (workspaceInfo.yaml)"
     env:
-      ARM_SUBSCRIPTION_ID: "{{.TF_VAR_subscription_id_1}}"
+      ARM_SUBSCRIPTION_ID: "{{.TF_VAR_subscription_id}}"
       AZ_TENANT_ID: "{{.AZ_TENANT_ID}}"
       AZ_CLIENT_SECRET: "{{.AZ_CLIENT_SECRET}}"
       AZ_CLIENT_ID: "{{.AZ_CLIENT_ID}}"
@@ -35,27 +35,19 @@ tasks:
 
         # Fetch individual cluster details from Terraform state
         pushd terraform > /dev/null
-        cluster1_name=$(terraform show -json terraform.tfstate | jq -r '
-          .values.outputs.cluster_1_name.value')
-        cluster1_server=$(terraform show -json terraform.tfstate | jq -r '
-          .values.outputs.cluster_1_fqdn.value')
-        cluster1_resource_group=$(terraform show -json terraform.tfstate | jq -r '
-          .values.outputs.cluster_1_rg.value')
-        cluster1_sub=$(terraform show -json terraform.tfstate | jq -r '
-          .values.outputs.cluster_1_sub.value')
+        cluster_name=$(terraform show -json terraform.tfstate | jq -r '
+          .values.outputs.cluster_name.value')
+        cluster_server=$(terraform show -json terraform.tfstate | jq -r '
+          .values.outputs.cluster_fqdn.value')
+        cluster_resource_group=$(terraform show -json terraform.tfstate | jq -r '
+          .values.outputs.cluster_rg.value')
+        cluster_sub=$(terraform show -json terraform.tfstate | jq -r '
+          .values.outputs.cluster_sub.value')
 
-        cluster2_name=$(terraform show -json terraform.tfstate | jq -r '
-          .values.outputs.cluster_2_name.value')
-        cluster2_server=$(terraform show -json terraform.tfstate | jq -r '
-          .values.outputs.cluster_2_fqdn.value')
-        cluster2_resource_group=$(terraform show -json terraform.tfstate | jq -r '
-          .values.outputs.cluster_2_rg.value')
-        cluster2_sub=$(terraform show -json terraform.tfstate | jq -r '
-          .values.outputs.cluster_2_sub.value')
         popd > /dev/null
 
         # Check if any of the required cluster variables are empty
-        if [ -z "$cluster1_name" ] || [ -z "$cluster1_server" ] || [ -z "$cluster1_resource_group" ]; then
+        if [ -z "$cluster_name" ] || [ -z "$cluster_server" ] || [ -z "$cluster_resource_group" ]; then
           echo "Error: Missing cluster details. Ensure Terraform plan has been applied."
           exit 1
         fi
@@ -67,35 +59,25 @@ tasks:
         defaultLocation: location-01
         defaultLOD: detailed
         cloudConfig:
+          kubernetes: null
           azure:
-            subscriptionId: "$ARM_SUBSCRIPTION_ID"
-            tenantId: "$AZ_TENANT_ID"
-            clientId: "$AZ_CLIENT_ID"
-            clientSecret: "$AZ_CLIENT_SECRET"
+            spSecretName: azure-sp
             aksClusters: 
               clusters: 
-                - name: $cluster1_name
-                  server: https://$cluster1_server:443
-                  resource_group: $cluster1_resource_group
-                  subscriptionId: $cluster1_sub
-                - name: $cluster2_name
-                  server: https://$cluster2_server:443
-                  resource_group: $cluster2_resource_group
-                  subscriptionId: $cluster2_sub
+                - name: $cluster_name
+                  server: https://$cluster_server:443
+                  resource_group: $cluster_resource_group
+                  subscriptionId: $cluster_sub
             resourceGroupLevelOfDetails:
-              $cluster1_resource_group: detailed
-              $cluster2_resource_group: detailed
+              $cluster_resource_group: detailed
         codeCollections: 
           - repoURL: "https://github.com/runwhen-contrib/rw-cli-codecollection"
             branch: "main"
             codeBundles: ["k8s-namespace-healthcheck", "azure-aks-triage", "k8s-deployment-healthcheck"]
-        # codeCollections: []
-        # - repoURL: "$repo_url"
-        #   branch: "$branch_name"
-        #   codeBundles: ["$codebundle"]
         custom: 
           kubernetes_distribution_binary: kubectl
         EOF
+
     silent: true
 
   run-rwl-discovery:
@@ -192,6 +174,111 @@ tasks:
         }
         echo "Terraform infrastructure build completed."
     silent: true
+
+  get-latest-rwl-tag: 
+    desc: Find the latest tag stored in the dev registry (usually these are created when the PR image build completes)
+    cmds: 
+      - | 
+        # Variables
+        REGION="us"                                     
+        PROJECT_ID="runwhen-nonprod-shared"             
+        REPO_NAME="public-images"                       
+        IMAGE_NAME="runwhen-local"               
+
+        # API endpoint for unauthenticated access
+        URL="https://$REGION-docker.pkg.dev/v2/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME/tags/list"
+
+        # Fetch tags and metadata
+        RESPONSE=$(curl -s "$URL")
+
+        # Check if the response is valid
+        if [[ -z "$RESPONSE" || "$(echo "$RESPONSE" | jq '.errors')" != "null" ]]; then
+          echo "Failed to fetch tags. Ensure the image is public and the URL is correct."
+          exit 1
+        fi
+
+        # Fetch the current branch name
+        BRANCH=$(git branch --show-current)
+
+        # Fetch the PR number (without #) associated with the branch using gh CLI
+        PR_ID=$(gh pr list --head "$BRANCH" --state open --json number -q '.[0].number')
+
+        # Check if a PR was found
+        if [[ -z "$PR_ID" ]]; then
+          echo "No open pull request found for branch: $BRANCH"
+          exit 1
+        fi
+
+        echo "Pull Request ID: $PR_ID"
+
+        # Extract and sort tags by timestamp
+        PR_TAG=$(echo "$RESPONSE" | jq -r '.tags' | grep "$PR_ID-" | xargs | tr -d ",")
+
+        echo "$PR_TAG is most likely the desired last build image from this branch - updating values.yaml"
+        yq -i ".runwhenLocal.image.tag = \"${PR_TAG}\"" values.yaml
+
+    silent: true
+
+
+  install-rwl-helm:
+    desc: Install RunWhen Local components into cluster
+    env: 
+      ARM_SUBSCRIPTION_ID: "{{.TF_VAR_subscription_id}}"
+      AZ_TENANT_ID: "{{.AZ_TENANT_ID}}"
+      AZ_CLIENT_SECRET: "{{.AZ_CLIENT_SECRET}}"
+      AZ_CLIENT_ID: "{{.AZ_CLIENT_ID}}"
+      RW_WORKSPACE: '{{.RW_WORKSPACE | default "my-workspace"}}'
+      RUNNER_TOKEN: "{{.RUNNER_TOKEN}}"
+    cmds: 
+     - | 
+        namespace=runwhen-local
+        kubectl create namespace $namespace || true
+        kubectl create configmap workspaceinfo --from-file=workspaceInfo.yaml -n $namespace
+        kubectl create secret generic runner-registration-token --from-literal=token="$RUNNER_TOKEN" -n $namespace || true
+        kubectl create secret generic azure-sp \
+          --from-literal=clientId=$AZ_CLIENT_ID \
+          --from-literal=clientSecret=$AZ_CLIENT_SECRET \
+          --from-literal=subscriptionId=$ARM_SUBSCRIPTION_ID \
+          --from-literal=tenantId=$AZ_TENANT_ID \
+          --namespace=$namespace  || true
+        helm repo add runwhen-contrib https://runwhen-contrib.github.io/helm-charts
+        helm repo update
+        helm install runwhen-local runwhen-contrib/runwhen-local -f values.yaml -n $namespace
+    silent: true
+
+  delete-rwl-helm:
+    desc: Install RunWhen Local components into cluster
+    env: 
+      ARM_SUBSCRIPTION_ID: "{{.TF_VAR_subscription_id}}"
+      AZ_TENANT_ID: "{{.AZ_TENANT_ID}}"
+      AZ_CLIENT_SECRET: "{{.AZ_CLIENT_SECRET}}"
+      AZ_CLIENT_ID: "{{.AZ_CLIENT_ID}}"
+      RW_WORKSPACE: '{{.RW_WORKSPACE | default "my-workspace"}}'
+      RUNNER_TOKEN: "{{.RUNNER_TOKEN}}"
+    cmds: 
+     - | 
+        namespace=runwhen-local
+        kubectl delete namespace $namespace
+    silent: true
+
+  upgrade-rwl-helm:
+    desc: Install RunWhen Local components into cluster
+    env: 
+      ARM_SUBSCRIPTION_ID: "{{.TF_VAR_subscription_id}}"
+      AZ_TENANT_ID: "{{.AZ_TENANT_ID}}"
+      AZ_CLIENT_SECRET: "{{.AZ_CLIENT_SECRET}}"
+      AZ_CLIENT_ID: "{{.AZ_CLIENT_ID}}"
+      RW_WORKSPACE: '{{.RW_WORKSPACE | default "my-workspace"}}'
+      RUNNER_TOKEN: "{{.RUNNER_TOKEN}}"
+    cmds: 
+     - | 
+        namespace=runwhen-local
+        kubectl delete configmap workspaceinfo -n $namespace || true
+        kubectl create configmap workspaceinfo --from-file=workspaceInfo.yaml -n $namespace
+        helm upgrade runwhen-local runwhen-contrib/runwhen-local -f values.yaml -n $namespace
+        kubectl delete pod -l app.kubernetes.io/name=runwhen-local -n runwhen-local
+
+
 
   cleanup-terraform-infra:
     desc: "Cleanup deployed Terraform infrastructure"
