x

diff --git a/.test/azure/aks-and-k8s/Taskfile.yaml b/.test/azure/aks-and-k8s/Taskfile.yaml
--- a/.test/azure/aks-and-k8s/Taskfile.yaml
+++ b/.test/azure/aks-and-k8s/Taskfile.yaml
@@ -5,6 +5,7 @@ tasks:
     desc: "Generate workspaceInfo and rebuild/test"
     cmds:
       - task: generate-rwl-config
+      - task: build-rwl  
       - task: run-rwl-discovery
 
   clean:
@@ -84,11 +85,11 @@ tasks:
         EOF
     silent: true
 
-  run-rwl-discovery:
-    desc: "Run RunWhen Local Discovery on test infrastructure"
+  build-rwl:
+    desc: "Build RWL test image"
     cmds:
       - |
-        BUILD_DIR=/home/runwhen/runwhen-local/src
+        BUILD_DIR=../../../src/
         CONTAINER_NAME="RunWhenLocal"
         if docker ps -q --filter "name=$CONTAINER_NAME" | grep -q .; then
           echo "Stopping and removing existing container $CONTAINER_NAME..."
@@ -106,6 +107,27 @@ tasks:
 
         ## Building Container Image
         docker buildx build --builder mybuilder --platform linux/amd64  -t runwhen-local:test -f $BUILD_DIR/Dockerfile $BUILD_DIR --load
+    silent: true
+
+  run-rwl-discovery:
+    desc: "Run RunWhen Local Discovery on test infrastructure"
+    cmds:
+      - |
+        rm slx_count.txt || true
+        CONTAINER_NAME="RunWhenLocal"    
+        if docker ps -q --filter "name=$CONTAINER_NAME" | grep -q .; then
+          echo "Stopping and removing existing container $CONTAINER_NAME..."
+          docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME
+        elif docker ps -a -q --filter "name=$CONTAINER_NAME" | grep -q .; then
+          echo "Removing existing stopped container $CONTAINER_NAME..."
+          docker rm $CONTAINER_NAME
+        else
+          echo "No existing container named $CONTAINER_NAME found."
+        fi
+        
+        echo "Cleaning up output directory..."
+        rm -rf output || { echo "Failed to remove output directory"; exit 1; }
+        mkdir output && chmod 777 output || { echo "Failed to set permissions"; exit 1; }
 
         echo "Starting new container $CONTAINER_NAME..."
 
@@ -119,9 +141,10 @@ tasks:
         }
 
         echo "Review generated config files under output/workspaces/"
-        echo "Total SLXs: $(find $(find 'output/' -type d -name 'slxs') -mindepth 1 -type d | wc -l)"
+        total_slxs=$(find $(find 'output/' -type d -name 'slxs') -mindepth 1 -type d | wc -l)
+        echo "Total SLXs: $total_slxs"
+        echo "$total_slxs" > slx_count.txt
     silent: true
-
 
   ci-test-1:
     desc: "Run CI Discovery Test 1 - K8s & AKS - defaultLOD None, K8s context defaultNamespaceLOD Basic, AKS defaultNamespaceLOD Detailed"
