fix aks tasks

diff --git a/.test/azure/aks-and-k8s/Taskfile.yaml b/.test/azure/aks-and-k8s/Taskfile.yaml
--- a/.test/azure/aks-and-k8s/Taskfile.yaml
+++ b/.test/azure/aks-and-k8s/Taskfile.yaml
@@ -609,11 +609,10 @@ tasks:
         task env-setup
         task format-and-init-terraform
         echo "Starting Terraform Build of Terraform infrastructure..."
-        terraform plan
-        # terraform apply -auto-approve -lock=false || {
-        #   echo "Failed to clean up Terraform infrastructure."
-        #   exit 1
-        # }
+        terraform apply -auto-approve -lock=false || {
+          echo "Failed to clean up Terraform infrastructure."
+          exit 1
+        }
         echo "Terraform infrastructure build completed."
 
     silent: true
