remove stale gitpod files. add back .secret gitignore. remove sudo from taskfile (sudo not in image)

diff --git a/.test/azure/multi-subscription-aks/Taskfile.yaml b/.test/azure/multi-subscription-aks/Taskfile.yaml
--- a/.test/azure/multi-subscription-aks/Taskfile.yaml
+++ b/.test/azure/multi-subscription-aks/Taskfile.yaml
@@ -116,7 +116,7 @@ tasks:
         fi
         
         echo "Cleaning up output directory..."
-        sudo rm -rf output || { echo "Failed to remove output directory"; exit 1; }
+        rm -rf output || { echo "Failed to remove output directory"; exit 1; }
         mkdir output && chmod 777 output || { echo "Failed to set permissions"; exit 1; }
 
         ## Building Container Image
@@ -141,7 +141,7 @@ tasks:
     cmds:
       - |
         # Source Envs for Auth
-        source terraform/tf.local
+        source terraform/tf.secret
 
         # Navigate to the Terraform directory
         if [ ! -d "terraform" ]; then
@@ -175,7 +175,7 @@ tasks:
     cmds:
       - |
         # Source Envs for Auth
-        source terraform/tf.local
+        source terraform/tf.secret
 
 
         # Navigate to the Terraform directory
@@ -199,7 +199,7 @@ tasks:
     cmds:
       - |
         # Source Envs for Auth
-        source terraform/tf.local
+        source terraform/tf.secret
 
         # Navigate to the Terraform directory
         if [ -d "terraform" ]; then
@@ -237,6 +237,6 @@ tasks:
     desc: "Check and clean up RunWhen Local discovery output"
     cmds:
       - |
-        sudo rm -rf output
+        rm -rf output
         rm workspaceInfo.yaml
     silent: true
