reduce test scope

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -56,34 +56,34 @@ env:
 #           task ci-test-2
           
 jobs:
-  build-image:
-    runs-on: ubuntu-latest
-    outputs:
-      image-tag: ${{ github.sha }}
-    steps:
-      - name: Install Task
-        uses: arduino/setup-task@v2
-        with:
-          version: 3.x
+  # build-image:
+    # runs-on: ubuntu-latest
+    # outputs:
+    #   image-tag: ${{ github.sha }}
+    # steps:
+    #   - name: Install Task
+    #     uses: arduino/setup-task@v2
+    #     with:
+    #       version: 3.x
 
-      - uses: actions/checkout@v2
-        name: Checkout
+    #   - uses: actions/checkout@v2
+    #     name: Checkout
 
-      - name: Build Image
-        run: |-
-          cd .test/k8s/basic
-          docker buildx create --use --name=mybuilder
-          docker buildx inspect --bootstrap
-          task build-rwl
-          docker save -o image.tar runwhen-local:test || (echo "Image not found!" && exit 1)
+    #   - name: Build Image
+    #     run: |-
+    #       cd .test/k8s/basic
+    #       docker buildx create --use --name=mybuilder
+    #       docker buildx inspect --bootstrap
+    #       task build-rwl
+    #       docker save -o image.tar runwhen-local:test || (echo "Image not found!" && exit 1)
 
 
-      - name: Upload Image as Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: container-image
-          path: .test/k8s/basic/image.tar
-          retention-days: 1
+    #   - name: Upload Image as Artifact
+    #     uses: actions/upload-artifact@v4
+    #     with:
+    #       name: container-image
+    #       path: .test/k8s/basic/image.tar
+    #       retention-days: 1
 
   # k8s-basic-test:
   #   needs: build-image
@@ -120,7 +120,7 @@ jobs:
   #         task ${{ matrix.test }}
 
   azure-aks-and-k8s:
-    needs: build-image
+    # needs: build-image
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -135,15 +135,15 @@ jobs:
       - uses: actions/checkout@v2
         name: Checkout
 
-      - name: Download Image Artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: container-image
-          path: .test/azure/aks-and-k8s
+      # - name: Download Image Artifact
+      #   uses: actions/download-artifact@v4
+      #   with:
+      #     name: container-image
+      #     path: .test/azure/aks-and-k8s
 
-      - name: Load Docker Image
-        run: |
-          docker load -i .test/azure/aks-and-k8s/image.tar
+      # - name: Load Docker Image
+      #   run: |
+      #     docker load -i .test/azure/aks-and-k8s/image.tar
 
       - name: Azure Login
         uses: azure/login@v2
